### ISSUE TITLE
Compatibility with LABjs and other Script Loaders

### ISSUE THREAD

**Issue by aresxc** [jcobb/basic-jquery-slider#154]
The load of resources normally is:
- jQuery
- bjqs.min.js
- bjqs.css

but, if We use a Script Loader like LABjs, the order is:
- bjqs.css
- jQuery
- bjqs.min.js

this causes some inconsistencies.

Inconsistencies:
The slider don't show content, after some seconds it's displayed..

Fix?

The best way to fix it, is modify bjsq.css.
Change:

``` css
ul.bjqs{position:relative; list-style:none;padding:0;margin:0;overflow:hidden; display:none;}
```

by:

``` css
ul.bjqs{position:relative; list-style:none;padding:0;margin:0;overflow:hidden;}
```

And:

``` css
li.bjqs-slide{position:absolute; display:none;}
```

by:

``` css
li.bjqs-slide{position:absolute;}
```

Thanks.
