### ISSUE TITLE
CSS file contains non-essential, invasive styles

### ISSUE THREAD

**Issue by NOtherDev** [jcobb/basic-jquery-slider#82]
basic-jquery-slider.css, described as "essential styles", contains style definitions that break existing page layouts:

``` css
/* demo styles */

body{
  background:#f5f5f5;
  font-family: 'Carter One', sans-serif;
}

#container{
  width:980px;
  padding:100px 0;
  margin:0 auto;
  overflow:hidden;
}

#banner {
  height:300px;
  width:700px;
  margin:0 auto;
  position:relative;
  background:#fff;
  border:20px #fff solid;
  box-shadow:0 0 50px rgba(0,0,0,0.5);
}
```

These should not be included as "essential styles".
